-- Every seed sold in the shop. Better seeds cost more and take longer to
-- grow, but once they bloom they attract rarer (more valuable) birds.
--
-- GrowTime     seconds from planting to full bloom
-- BirdInterval {min, max} seconds between bird visits once blooming
-- Birds        weighted list of the birds this plant attracts
-- Stock        chance the shop has this seed after a restock, and how many

local function rgb(r, g, b)
	return Color3.fromRGB(r, g, b)
end

local Seeds = {}

Seeds.List = {
	{
		Id = "Sunflower",
		Name = "Sunflower",
		Icon = "🌻",
		Rarity = "Common",
		Price = 10,
		GrowTime = 30,
		BirdInterval = { 10, 20 },
		Stock = { Chance = 1, Min = 8, Max = 14 },
		Birds = {
			{ Id = "Sparrow", Weight = 55 },
			{ Id = "Pigeon", Weight = 35 },
			{ Id = "Goldfinch", Weight = 10 },
		},
		Description = "A cheerful flower packed with tasty seeds.",
		Look = {
			Style = "Flower",
			StemHeight = 5.2,
			StemWidth = 1.2,
			StemColor = rgb(80, 140, 50),
			LeafColor = rgb(70, 150, 50),
			Leaves = 3,
			Heads = 1,
			HeadTilt = 25,
			PetalColor = rgb(255, 205, 30),
			PetalCount = 14,
			PetalLength = 1.0,
			PetalWidth = 0.42,
			CenterColor = rgb(110, 70, 30),
			CenterSize = 1.5,
		},
	},
	{
		Id = "BerryBush",
		Name = "Berry Bush",
		Icon = "🍒",
		Rarity = "Common",
		Price = 30,
		GrowTime = 75,
		BirdInterval = { 12, 22 },
		Stock = { Chance = 1, Min = 4, Max = 8 },
		Birds = {
			{ Id = "Robin", Weight = 50 },
			{ Id = "Sparrow", Weight = 30 },
			{ Id = "BlueJay", Weight = 15 },
			{ Id = "Cardinal", Weight = 5 },
		},
		Description = "Juicy red berries that robins adore.",
		Look = {
			Style = "Bush",
			LeafColor = rgb(55, 130, 55),
			BerryColor = rgb(200, 30, 60),
		},
	},
	{
		Id = "Lavender",
		Name = "Lavender",
		Icon = "💜",
		Rarity = "Uncommon",
		Price = 90,
		GrowTime = 180,
		BirdInterval = { 14, 26 },
		Stock = { Chance = 0.85, Min = 2, Max = 5 },
		Birds = {
			{ Id = "Goldfinch", Weight = 40 },
			{ Id = "BlueJay", Weight = 30 },
			{ Id = "Cardinal", Weight = 25 },
			{ Id = "Hummingbird", Weight = 5 },
		},
		Description = "Fragrant purple spikes buzzing with life.",
		Look = {
			Style = "Spike",
			StemHeight = 2.6,
			Stems = 8,
			StemColor = rgb(90, 130, 80),
			LeafColor = rgb(120, 150, 110),
			FlowerColor = rgb(150, 110, 220),
		},
	},
	{
		Id = "Hibiscus",
		Name = "Hibiscus",
		Icon = "🌺",
		Rarity = "Uncommon",
		Price = 250,
		GrowTime = 300,
		BirdInterval = { 15, 28 },
		Stock = { Chance = 0.65, Min = 1, Max = 4 },
		Birds = {
			{ Id = "Hummingbird", Weight = 45 },
			{ Id = "Cardinal", Weight = 30 },
			{ Id = "Goldfinch", Weight = 20 },
			{ Id = "Parrot", Weight = 5 },
		},
		Description = "Big tropical blooms full of sweet nectar.",
		Look = {
			Style = "Flower",
			StemHeight = 2.8,
			StemColor = rgb(60, 110, 45),
			LeafColor = rgb(40, 120, 50),
			Leaves = 5,
			Heads = 3,
			HeadSpread = 1.3,
			HeadTilt = 72,
			PetalColor = rgb(235, 50, 90),
			PetalCount = 5,
			PetalLength = 1.3,
			PetalWidth = 1.1,
			CenterColor = rgb(255, 220, 90),
			CenterSize = 0.4,
		},
	},
	{
		Id = "MangoTree",
		Name = "Mango Tree",
		Icon = "🥭",
		Rarity = "Rare",
		Price = 700,
		GrowTime = 600,
		BirdInterval = { 15, 30 },
		Stock = { Chance = 0.45, Min = 1, Max = 3 },
		Birds = {
			{ Id = "Parrot", Weight = 50 },
			{ Id = "Hummingbird", Weight = 35 },
			{ Id = "Toucan", Weight = 15 },
		},
		Description = "A shady tree heavy with ripe mangoes.",
		Look = {
			Style = "Tree",
			TrunkHeight = 4.5,
			TrunkColor = rgb(110, 75, 45),
			LeafColor = rgb(60, 140, 60),
			FruitColor = rgb(255, 170, 40),
			FruitSize = 0.6,
		},
	},
	{
		Id = "Lotus",
		Name = "Pink Lotus",
		Icon = "🌸",
		Rarity = "Rare",
		Price = 1800,
		GrowTime = 900,
		BirdInterval = { 18, 32 },
		Stock = { Chance = 0.3, Min = 1, Max = 2 },
		Birds = {
			{ Id = "Flamingo", Weight = 45 },
			{ Id = "Parrot", Weight = 35 },
			{ Id = "Toucan", Weight = 15 },
			{ Id = "Peacock", Weight = 5 },
		},
		Description = "A calm little pond with a glowing lotus.",
		Look = {
			Style = "Lotus",
			PetalColor = rgb(255, 140, 190),
			InnerPetalColor = rgb(255, 200, 225),
			CenterColor = rgb(255, 220, 90),
			PadColor = rgb(70, 150, 70),
		},
	},
	{
		Id = "Moonflower",
		Name = "Moonflower",
		Icon = "🌙",
		Rarity = "Epic",
		Price = 5000,
		GrowTime = 1500,
		BirdInterval = { 20, 35 },
		Stock = { Chance = 0.18, Min = 1, Max = 1 },
		Birds = {
			{ Id = "SnowyOwl", Weight = 40 },
			{ Id = "Flamingo", Weight = 25 },
			{ Id = "Toucan", Weight = 25 },
			{ Id = "Peacock", Weight = 10 },
		},
		Description = "Glowing silver petals that shine like the moon.",
		Look = {
			Style = "Flower",
			StemHeight = 3.1,
			StemColor = rgb(40, 90, 80),
			LeafColor = rgb(50, 110, 95),
			Leaves = 6,
			Heads = 3,
			HeadSpread = 1.4,
			HeadTilt = 72,
			PetalColor = rgb(200, 215, 255),
			PetalMaterial = Enum.Material.Neon,
			PetalCount = 5,
			PetalLength = 1.15,
			PetalWidth = 1.1,
			CenterColor = rgb(240, 245, 255),
			CenterSize = 0.45,
			Glow = rgb(170, 200, 255),
		},
	},
	{
		Id = "GoldenTree",
		Name = "Golden Tree",
		Icon = "🌟",
		Rarity = "Legendary",
		Price = 15000,
		GrowTime = 2400,
		BirdInterval = { 22, 38 },
		Stock = { Chance = 0.08, Min = 1, Max = 1 },
		Birds = {
			{ Id = "Peacock", Weight = 45 },
			{ Id = "SnowyOwl", Weight = 35 },
			{ Id = "Toucan", Weight = 15 },
			{ Id = "Phoenix", Weight = 5 },
		},
		Description = "A shimmering tree with leaves of pure gold.",
		Look = {
			Style = "Tree",
			TrunkHeight = 4.8,
			TrunkColor = rgb(240, 225, 190),
			LeafColor = rgb(255, 200, 50),
			LeafReflectance = 0.15,
			FruitColor = rgb(255, 245, 180),
			FruitMaterial = Enum.Material.Neon,
			FruitSize = 0.55,
			Sparkle = true,
			Glow = rgb(255, 210, 90),
		},
	},
	{
		Id = "EmberBloom",
		Name = "Ember Bloom",
		Icon = "🔥",
		Rarity = "Mythic",
		Price = 50000,
		GrowTime = 3600,
		BirdInterval = { 25, 40 },
		Stock = { Chance = 0.03, Min = 1, Max = 1 },
		Birds = {
			{ Id = "Phoenix", Weight = 35 },
			{ Id = "Peacock", Weight = 35 },
			{ Id = "SnowyOwl", Weight = 30 },
		},
		Description = "A flower of living flame. Legends say it calls the Phoenix.",
		Look = {
			Style = "Flower",
			StemHeight = 4.6,
			StemWidth = 1.2,
			StemColor = rgb(60, 30, 30),
			LeafColor = rgb(130, 45, 30),
			Leaves = 3,
			Heads = 1,
			HeadTilt = 35,
			PetalColor = rgb(255, 90, 20),
			InnerPetalColor = rgb(255, 180, 40),
			PetalMaterial = Enum.Material.Neon,
			PetalCount = 8,
			PetalLength = 1.8,
			PetalWidth = 0.8,
			CenterColor = rgb(255, 230, 120),
			CenterMaterial = Enum.Material.Neon,
			CenterSize = 0.9,
			Fire = true,
			Glow = rgb(255, 140, 50),
		},
	},
}

Seeds.ById = {}
for index, seed in ipairs(Seeds.List) do
	seed.Order = index
	Seeds.ById[seed.Id] = seed
end

function Seeds.Get(id)
	return Seeds.ById[id]
end

return Seeds
